### PR TITLE
Add figure shortcode for diagrams

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a `figure` shortcode for presenting technical diagrams. This shortcode enables you to provide a caption and specify the width of the image. You can see example usages here:

https://deploy-preview-60--spiffe.netlify.com/spire/overview/

### CODE REVIEW

**Comment by lucperkins** [comment]
@jennybeth No prob!

**Comment by jennybeth** [comment]
Pardon my ignorance, what is the syntax to invoke the figure shortcode in the source?

**Comment by lucperkins** [comment]
@jennybeth You can see usage examples in the SPIRE Overview doc

**Comment by jennybeth** [comment]
@lucperkins 

In here: https://raw.githubusercontent.com/spiffe/spiffe.io/master/content/spire/overview.md?

**Comment by lucperkins** [comment]
@jennybeth No, in this pull request

**Comment by jennybeth** [comment]
@lucperkins 

Blammo!

{{< figure src="/img/server_and_agent.png" width="70" caption="Server and Agent" >}}

Thank you so much.

**Pull request merged**
