### PR TITLE
Adds Solving the Bottom Turtle book to the static site content.

### LINKED ISSUE #258: spiffe.io/book link is unavailable
as @evan2645 mentioned during the last sig-community call initially, we thought that the "Solving the bottom turtle" book will be hosted separately and not on the `spiffe.io` website. Thus thebottomturtle.io domain was used for it. 
Later `spife.io/book` section was added, and it referenced `https://thebottomturtle.io/Solving-the-bottom-turtle-SPIFFE-SPIRE-Book.pdf `.
Since the pdf was hosted on 3rd party website that had an expired certificate pdf became unavailable and later I updated `thebottomturtle.io` to redirect to `spiffe.io/book` which completely broke book availability.
The best way to solve these issues is to consolidate all assets under `spiffe.io`. We should put a pdf of the book as a static resource and fix the links.

### PR DESCRIPTION
**Pull request by elinesterov**
This pr fixes #258 

Adds Solving the Bottom Turtle book to the static site content. Fixes links.

Tested via https://6356de8d4fa5e10f981965f9--monumental-klepon-bbaacb.netlify.app/book/

### CODE REVIEW

**Review by mchurichi — APPROVED** [review]
Thanks for this, Eli 🙌

**Comment by elinesterov** [comment]
@mchurichi np! It took a while. Hope changes will show up soon

**Comment by mchurichi** [comment]
Changes are live now

**Comment by elinesterov** [comment]
>Changes are live now

Thank you for checking and confirming @mchurichi!

**Pull request merged**
