### PR TITLE
Import using_spire.md from github

### PR DESCRIPTION
**Pull request by sanderson042**
This document replaces the "Get SPIRE" link in the left nav. That
linked directly to "Get SPIRE" on the spiffe.io home page. Since the
Get SPIRE page has a slightly different look and feel than most of the
docs, this link was kind of jarring. This new document displays more
information about getting SPIRE in the same format as the rest of the
doc pages. This document has been named "Getting SPIRE" to
differentiate it slightly from the "Get SPIRE" page just referenced.

Signed-off-by: Steve Anderson <steve.anderson@hpe.com>

### CODE REVIEW

**Comment by mchurichi** [comment]
Hey Steve 👋 thanks for adding this!
While testing locally, I noticed two issues with the hyperlinks that are unrelated to your changes:

1. The link on `SPIRE 101` doesn't work properly. It points to an unexisting github url (it's missing a piece on the url). Also, it should point to the SPIRE101 url we are already importing.
2. Links to the spiffe.io website are opened in a new tab/window. This is not how they work on the markdown your write on the spiffe.io repo itself, and it is not how they should work on imported github files either. Links to the same site should be opened in the same tab/window, only external links should be opened in a new one

I will open a new PR shortly addressing these issues, but in the meantime I would like to keep this PR open so we don't push content that doesn't work as intended.

**Comment by sanderson042** [comment]
Sure, sounds good, thanks Max 👍

**Review by mchurichi — APPROVED** [review]
Looks good!, thanks
We can merge this as soon as we merge #181

**Comment by mchurichi** [comment]
@sanderson042 are we now ok to merge this?

**Comment by sanderson042** [comment]
> @sanderson042 are we now ok to merge this?

Yes, we can merge this now 👍

**Pull request merged**
