### PR TITLE
Istio doesn't use Citadel as a separate concept any more

### PR DESCRIPTION
**Pull request by craigbox**
Updated to link to a new page.

### CODE REVIEW

**Review by ajessup — APPROVED** [review]

**Review by anvega — APPROVED** [review]

**Comment by sanderson042** [comment]
This merge is hung up on a DCO check fail. I think @drrt can help me resolve it.

**Comment by sanderson042** [comment]
Hi @craigbox - Thanks very much for the correction! We appreciate you taking the time.

There's a little glitch with your PR in that it is missing the Developer Code of Origin (DCO) signoff. You should be able to fix it by following the two steps in option 1 of this document from another OSS project:

https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#fix-option-1-amend-single-commit

I thought we might be able to fix it on our end but we couldn't.

**Comment by craigbox** [comment]
sigh, thanks DCO and/or GitHub's edit UI for making drive-by commits tedious

(fixed)

**Comment by sanderson042** [comment]
Hi @craigbox 👋  Yes, I definitely agree - lack of support for DCO in the GitHub edit UI has tripped me up also. Anyway, thanks for the original fix and the DCO fix!

**Pull request merged**
