### PR TITLE
Added new section for putting links to examples of use of spiffe client libraries

### PR DESCRIPTION
**Pull request by martincapello**
This PR adds only a new markdown file to contains links to the actual README.md files on other repositories. I did this because there is work in progress to improve how the documentation is managed to avoid duplicated information, so this is just a quick and temporary fix.

### CODE REVIEW

**Comment by sanderson042** [comment]
Hi Martin - I hope you don't mind, I revamped this a bit. Let me know what you think.

I had some git issues uploading my new version to your branch so I just attached it here (GitHub wouldn't let me attach a .md file, so I temporarily added a .txt suffix). I've also suggested a new name for the file. 

[code-samples.md.txt](https://github.com/spiffe/spiffe.io/files/4626631/code-samples.md.txt)

**Comment by martincapello** [comment]
Hi Steve, the idea of the new section I added is to show links to READMEs that explain how to use the different libraries inside an application, instead of how to deal with the Workload API.
For instance, the go-spiffe library uses the Workload API internally, but the README I linked is about how to use the library, not the Workload API. The same is going to happen with the java-spiffe library. What I'm trying to say is that the library is not just a set of functions that reflect the Workload API, instead it is a module that allows the user to avoid dealing with several of the details of the Workload API, providing functionality to establish (an maintain) SPIFFE-enabled connections transparently.
So, I believe that where you say "Workload API Code Samples" it should say something like "SPIFFE library usage samples" or "Using the SPIFFE library".
About the description, the library doesn't provides functions to create bundles, nor generating SVIDs, these are tasks that SPIRE server does internally. The library provides functions to fetch SVIDs and trust bundles using the Workload API.

**Comment by sanderson042** [comment]
Hi Martin, thanks for explaining the issues with my version. I appreciate the honest feedback. I've attached a newer version. Please take another look.
[library-code-samples.md.txt](https://github.com/spiffe/spiffe.io/files/4637359/library-code-samples.md.txt)

**Comment by martincapello** [comment]
Hey Steve, I liked this new version! I just made a really small change..on the overview paragraph I avoided mentioning the specific names of libraries and languages that are currently supported, because we also have an outdated C++ version (c-spiffe), and I'm nor sure how many more languages we are going to support (or maybe the community could make their ports and we might reference them here), hence I'm trying to avoid having to update the text any time a new library becomes available.

**Pull request merged**
