### PR TITLE
Improve Getting Started Guide for Kubernetes

### PR DESCRIPTION
**Pull request by ryysud**
The changes are below.

- Fix incorrect descriptions such as "The agent-configmap.yaml file ~" or "socketagent.sock" correctly
- Add a `Register Workloads` section to see a list of SVIDs, not error messages

Please point out if the description in the `Register Workloads` section is not enough...

### CODE REVIEW

**Comment by ryysud** [comment]
@ajessup @jennybeth Please review.

**Comment by ajessup** [comment]
LGTM, thanks @ryysud! I'll wait for Jenny's approval before we merge.

**Comment by ryysud** [comment]
OK! Thank you for your review :)

**Comment by ryysud** [comment]
@jennybeth Please review. ( cc: @ajessup )

**Comment by ryysud** [comment]
Thank you for your review!

**Pull request merged**
